/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dominpg;

import gui.Gui;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false); // Không cho phép thay đổi kích thước
        setSize(805, 830);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_HowToPlay = new javax.swing.JButton();
        btn_AboutUs = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_PlayGame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minesweeper Game");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_HowToPlay.setBackground(new java.awt.Color(255, 255, 255));
        btn_HowToPlay.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_HowToPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HowToPlay.jpg"))); // NOI18N
        btn_HowToPlay.setText(" How to play");
        btn_HowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HowToPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btn_HowToPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, 310, -1));

        btn_AboutUs.setBackground(new java.awt.Color(255, 255, 255));
        btn_AboutUs.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_AboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AboutUs.jpg"))); // NOI18N
        btn_AboutUs.setText("  About us ");
        btn_AboutUs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AboutUsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, 310, -1));

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_exit.setText("Quit ");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 730, 310, -1));

        btn_PlayGame.setBackground(new java.awt.Color(255, 255, 255));
        btn_PlayGame.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_PlayGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.jpg"))); // NOI18N
        btn_PlayGame.setText(" Play game");
        btn_PlayGame.setAutoscrolls(true);
        btn_PlayGame.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_PlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlayGameActionPerformed(evt);
            }
        });
        getContentPane().add(btn_PlayGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 310, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuBackGround.jpg"))); // NOI18N
        jLabel5.setAutoscrolls(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Goodbye and see you again!");
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AboutUsActionPerformed
        // TODO add your handling code here:
        JframeAboutUs jAB = new JframeAboutUs();
        jAB.show();
        dispose();
    }//GEN-LAST:event_btn_AboutUsActionPerformed

    private void btn_HowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HowToPlayActionPerformed
        // TODO add your handling code here:
        HowToPlay jAB = new HowToPlay();
        jAB.show();
        dispose();
    }//GEN-LAST:event_btn_HowToPlayActionPerformed

    private void btn_PlayGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlayGameActionPerformed
        // TODO add your handling code here:

        Gui gui = new Gui();
        gui.show();
        dispose();
    }//GEN-LAST:event_btn_PlayGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AboutUs;
    private javax.swing.JButton btn_HowToPlay;
    private javax.swing.JButton btn_PlayGame;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
